export default {
  '11'  : 'cielo despejado',
  '11n' : 'despejado noche',
  '12'  : 'poco nuboso',
  '12n' : 'poco nuboso noche',
  '13'  : 'Intervalos nubosos',
  '13n' : 'intervalos nubosos noche',
  '14'  : 'nuboso',
  '14n' : 'nuboso noche',
  '15'  : 'muy nuboso',
  '16'  : 'cubierto',
  '17'  : 'nubes altas',
  '17n' : 'nubes altas noche',
  '43'  : 'intervalos nubosos con lluvia escasa',
  '43n' : 'intervalos nubosos con lluvia escasa noche',
  '44'  : 'nuboso con lluvia escasa',
  '44n' : 'nuboso con lluvia escasa noche',
  '45'  : 'muy nuboso con lluvia escasa',
  '46'  : 'cubierto con lluvia escasa',
  '23'  : 'intervalos nubosos con lluvia',
  '23n' : 'intervalos nubosos con lluvia noche',
  '24'  : 'nuboso con lluvia',
  '24n' : 'nuboso con lluvia noche',
  '25'  : 'muy nuboso con lluvia',
  '26'  : 'cubierto con lluvia',
  '71'  : 'intervalos nubosos con nieve escasa',
  '71n' : 'intervalos nubosos con nieve escasa noche',
  '72'  : 'nuboso con nieve escasa',
  '72n' : 'nuboso con nieve escasa noche',
  '73'  : 'muy nuboso con nieve escasa',
  '74'  : 'cubierto con nieve escasa',
  '33'  : 'intervalos nubosos con nieve',
  '33n' : 'intervalos nubosos con nieve noche',
  '34'  : 'nuboso con nieve',
  '34n' : 'nuboso con nieve noche',
  '35'  : 'muy nuboso con nieve',
  '36'  : 'cubierto con nieve',
  '51'  : 'intervalos nubosos con tormenta',
  '51n' : 'intervalos nubosos con tormenta noche',
  '52'  : 'nuboso con tormenta',
  '52n' : 'nuboso con tormenta noche',
  '53'  : 'muy nuboso con tormenta',
  '54'  : 'cubierto con tormenta',
  '61'  : 'intervalos nubosos con tormenta y lluvia escasa',
  '61n' : 'intervalos nubosos con tormenta y lluvia escasa noche',
  '62'  : 'nuboso con tormenta y lluvia escasa',
  '62n' : 'nuboso con tormenta y lluvia escasa noche',
  '63'  : 'muy nuboso con tormenta y lluvia escasa',
  '64'  : 'cubierto con tormenta y lluvia escasa',
  '81'  : 'niebla',
  '82'  : 'bruma',
  '83'  : 'calima',
};